<!-- clf2-nsi2 theme begins / Début du thème clf2-nsi2 -->
		<!-- Message space begins / Début de l'espace de message -->
		<div id="cn-msg-space">
			<div id="cn-upper-msg"></div>
			<div id="cn-lower-msg">
				<p id="cn-left-msg">Nom de l'institution</p>
				<p id="cn-right-msg" lang="en" xml:lang="en">Name of Institution</p>
			</div>
		</div>
		<!-- Message space ends / Fin de l'espace de message -->

		<div>
			<ul id="cn-ef-lang-links">
				<li><a href="theme-clf2-nsi2/xhtml/3col-theme-clf2-nsi2-xhtml-fra.html" title="Français - Version française de ce site Web">Français</a></li>
				<li lang="en" xml:lang="en"><a href="theme-clf2-nsi2/xhtml/3col-theme-clf2-nsi2-xhtml-eng.html" title="English - English version of the Web site">English</a></li>
			</ul>
			<div id="cn-wmms"><img src="theme-clf2-nsi2/images/wmms.gif" width="83" height="20" alt="Symbole du gouvernement du Canada / Symbol of the Government of Canada" title="Symbole du gouvernement du Canada / Symbol of the Government of Canada" /></div>
			<ul id="cn-other-lang-links">
				<li lang="de" xml:lang="de"><a href="#">Deutsch</a></li>
				<li lang="es" xml:lang="es"><a href="#">Espa&#241;ol</a></li>
				<li lang="it" xml:lang="it"><a href="#">Italiano</a></li>
				<li lang="pt" xml:lang="pt"><a href="#">Português</a></li>
				<li lang="ru" xml:lang="ru"><a href="#">&#1056;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;</a></li>
			</ul>
		</div>	
<!-- clf2-nsi2 theme ends / Fin du thème clf2-nsi2 -->
